apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      initContainers:
      - name: wait-for-backend
        image: busybox
        command:
          - sh
          - -c
          - |
            until nc -z backend 5000; do
              echo "Waiting for Backend..."
              sleep 5
            done
      containers:
        - name: frontend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: 80

          env:
            - name: API_URL
              value: {{ .Values.env.API_URL | quote }}
