name: Deploy ECS Application

on:
  workflow_dispatch:
    
permissions:
  contents: read

env:
  FRONTEND_REPO: frontend-app
  BACKEND_REPO: backend-app
  CLUSTER: 3T-ECS
  SERVICE: 3T-ECS-Service

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: us-east-1

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Frontend Image
        run: |
          docker build \
            -t ${{ steps.login-ecr.outputs.registry }}/${{ env.FRONTEND_REPO }}:latest \
            ./frontend

      - name: Push Frontend Image
        run: |
          docker push \
            ${{ steps.login-ecr.outputs.registry }}/${{ env.FRONTEND_REPO }}:latest

      - name: Build Backend Image
        run: |
          docker build \
            -t ${{ steps.login-ecr.outputs.registry }}/${{ env.BACKEND_REPO }}:latest \
            ./backend

      - name: Push Backend Image
        run: |
          docker push \
            ${{ steps.login-ecr.outputs.registry }}/${{ env.BACKEND_REPO }}:latest

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Validate
        working-directory: terraform
        run: terraform validate

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve
        
      - name: ECS Deployment
        run: |
         aws ecs update-service \
         --cluster ${{ env.CLUSTER }} \
         --service ${{ env.SERVICE }} \
         --force-new-deployment
