name: Terraform

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Choose action"
        required: true
        type: choice
        options:
          - create
          - destroy

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - uses: hashicorp/setup-terraform@v3

      - run: terraform init
        working-directory: terraform

      - name: Create Infra
        if: github.event.inputs.action == 'create'
        run: | 
          terraform apply \
          -target=module.vpc \
          -target=module.sg \
          -target=module.cw \
          -auto-approve
        working-directory: terraform

      - name: Destroy Infra
        if: github.event.inputs.action == 'destroy'
        run: terraform destroy -auto-approve
        working-directory: terraform
