name: Deploy

on:
  workflow_dispatch: 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build Backend
      run: |
         docker build -t backend-app ./backend

    - name: Build Frontend
      run: |
         docker build -t frontend-app ./frontend    

    - name: Tag Backend
      run: |
        docker tag backend-app:latest \
        ${{ steps.login-ecr.outputs.registry }}/backend-app

    - name: Tag Frontend
      run: |
        docker tag frontend-app:latest \
        ${{ steps.login-ecr.outputs.registry }}/frontend-app
    
    - name: Push Backend
      run: |
        docker push \
        ${{ steps.login-ecr.outputs.registry }}/backend-app
    
    - name: Push Frontend
      run: |
        docker push \
        ${{ steps.login-ecr.outputs.registry }}/frontend-app

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          aws ecr get-login-password --region us-east-1 | \
          docker login --username AWS --password-stdin \
          ${{ steps.login-ecr.outputs.registry }}

          docker pull \
          ${{ steps.login-ecr.outputs.registry }}/backend-app:latest
          
          docker pull \
          ${{ steps.login-ecr.outputs.registry }}/frontend-app:latest
          
          sudo docker network rm mynet || true

          sudo docker rm -f backend frontend mysql || true

          sudo docker network create mynet
          
          sudo docker run -d --name mysql --network mynet -e MYSQL_ROOT_PASSWORD=rootpass -e MYSQL_USER=appuser -e MYSQL_DATABASE=student_registration -e MYSQL_PASSWORD=password123 mysql:8.0
          
          sleep 30
          
          sudo docker run -d -p 5000:5000 --name backend --network mynet -e DB_HOST=mysql -e DB_USER=appuser -e DB_PASSWORD=password123 -e DB_NAME=student_registration 160900807677.dkr.ecr.us-east-1.amazonaws.com/backend-app:latest
          
          sudo docker run -d -p 80:80 --name frontend --network mynet 160900807677.dkr.ecr.us-east-1.amazonaws.com/frontend-app:latest
